In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#import re
#from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
#from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
data1 = pd.read_csv("/content/drive/MyDrive/adult.csv")

In [4]:
data1.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [5]:
kt = []
m = range(15)
for i in range(len(data1.iloc[:, 0])):    
  sot = data1.iloc[i, :]                      
  if "?" not in set(sot):                 
    kt.append(sot)

In [6]:
k = np.array(kt)

In [7]:
lf = []
hf = []
for iv in k:
  if iv[14] == '<=50K':
    lf.append(iv)
  elif iv[14] == '>50K':
    hf.append(iv)

In [8]:
print(len(lf))

34014


In [9]:
lfa = np.array(lf)
hfa = np.array(hf)
tlf = np.transpose(lfa)
thf = np.transpose(hfa)

In [10]:
jak = np.concatenate((tlf, thf), axis=1)
print(jak.shape)

(15, 45222)


In [11]:
jt = []
for i in range(15):
  label_encoder = LabelEncoder()
  inte_jt = label_encoder.fit_transform(jak[i])
  jt.append(np.transpose(inte_jt))

In [12]:
jf = np.array(jt)
xj = np.transpose(jf[0:13])  #Feature matrix
yj = np.transpose(jf[14])    # Target Matrix

In [13]:
print(xj)

[[    8     2 18119 ...     0     0    39]
 [   21     2  3913 ...     0     0    49]
 [   17     2 15397 ...     0     0    29]
 ...
 [   36     2 23266 ...     0     0    39]
 [   23     2  9896 ...     0     0    39]
 [   35     3 21876 ...   110     0    39]]


In [14]:
# splitting data -> train 70%, test 15%, validation 15% (total 20400)
X_train, X_test, y_train, y_test = train_test_split(xj,yj, test_size=0.15,random_state=1)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train,test_size=0.17645,random_state=1)

# converting list to ndarray and converting datatypes
X_train = np.asarray(X_train, dtype=np.float)
X_test = np.asarray(X_test, dtype=np.float)
X_val = np.asarray(X_val, dtype=np.float)
y_train = np.asarray(y_train, dtype=np.uint8)
y_test = np.asarray(y_test, dtype=np.uint8)
y_val = np.asarray(y_val, dtype=np.uint8)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.float` is a deprecat

In [20]:
# create model
model = KNeighborsClassifier(metric="manhattan", n_neighbors=1)

# training
model.fit(X_train, y_train)

# testing
y_pred = model.predict(X_test)

In [21]:
y_pred

array([1, 0, 0, ..., 0, 0, 1], dtype=uint8)

In [17]:
# create model
model = GaussianNB()

# training
model.fit(X_train, y_train)

GaussianNB()

In [18]:
y_pred = model.predict(X_test)

In [19]:
y_pred

array([0, 0, 1, ..., 0, 0, 1], dtype=uint8)